# Generated by Django 4.2.5 on 2023-09-15 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('useremail', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrevCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_img', models.ImageField(upload_to='')),
                ('pc_title', models.CharField(max_length=100)),
                ('pc_description', models.TextField()),
                ('pc_lawyers', models.CharField(max_length=200)),
                ('pc_result', models.TextField()),
                ('pc_more_details', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_suspect', models.CharField(max_length=20)),
                ('case_number', models.CharField(max_length=50)),
                ('case_type', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('case_judge', models.CharField(max_length=20)),
                ('case_lawyer', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('prev_hearing_date', models.DateTimeField()),
                ('next_hearing_date', models.DateTimeField()),
                ('case_location', models.TextField()),
                ('case_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
