# Generated by Django 4.2.5 on 2023-09-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetails',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='casedetails',
            name='case_number',
        ),
    ]
