# Generated by Django 4.2.5 on 2023-09-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_portal_app', '0003_remove_prevcases_pc_img_remove_prevcases_pc_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevcases',
            name='pc_lawyers',
        ),
        migrations.RemoveField(
            model_name='prevcases',
            name='pc_more_details',
        ),
    ]
